In [17]:
from re import S
import pandas as pd
space = pd.read_csv('space.csv', sep=';'  )
spacex =space[space['Company Name']=='SpaceX']
maaiorCusto = spacex[' Cost'].max()
maaiorCusto

90.0

In [25]:
from re import S
import pandas as pd
space = pd.read_csv('space.csv', sep=';'  )

missoes =  space['Company Name'].value_counts()
missoes

RVSN USSR           1777
Arianespace          279
CASC                 251
General Dynamics     251
NASA                 203
VKS RF               201
US Air Force         161
ULA                  140
Boeing               136
Martin Marietta      114
SpaceX               100
MHI                   84
Northrop              83
Lockheed              79
ISRO                  76
Roscosmos             55
ILS                   46
Sea Launch            36
ISAS                  30
Kosmotras             22
US Navy               17
ISA                   13
Rocket Lab            13
Eurockot              13
ESA                   13
Blue Origin           12
IAI                   11
ExPace                10
ASI                    9
CNES                   8
AMBA                   8
MITT                   7
JAXA                   7
Land Launch            7
UT                     5
KCST                   5
CASIC                  5
Exos                   4
CECLES                 4
Arm??e de l'Air        4
KARI                   3
SRC                    3
AEB                    3
RAE                    2
OKB-586                2
Yuzhmash               2
Landspace              1
Douglas                1
EER                    1
Starsem                1
Virgin Orbit           1
IRGC                   1
i-Space                1
OneSpace               1
Sandia                 1
Khrunichev             1
Name: Company Name, dtype: int64